### ISSUE TITLE
self-test failures in v0.4.5

### ISSUE THREAD

**Issue by mandree** [noumar/iso639#8]
There are three issues with the self-test, and I am using Python 3.7.7 and pycountry 18.5.26.

```
[mandree@freebsd /usr/ports.svn/textproc/py-iso-639/work-py37/iso639-0.4.5]$ python -m unittest tests/tests.py 
..../usr/ports.svn/textproc/py-iso-639/work-py37/iso639-0.4.5/tests/tests.py:115: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  self.assertIsInstance(languages, collections.Iterable)
/usr/ports.svn/textproc/py-iso-639/work-py37/iso639-0.4.5/tests/tests.py:116: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  self.assertIsInstance(iter(languages), collections.Iterator)
...........E....F.
======================================================================
ERROR: setUpClass (tests.tests.CompatibilityChecks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports.svn/textproc/py-iso-639/work-py37/iso639-0.4.5/tests/tests.py", line 132, in setUpClass
    cls.pcterm = set(pclanguages.indices['terminology'].keys())
AttributeError: 'Languages' object has no attribute 'indices'

======================================================================
FAIL: test_logic_part2 (tests.tests.LogicFunctionality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports.svn/textproc/py-iso-639/work-py37/iso639-0.4.5/tests/tests.py", line 206, in test_logic_part2
    self.assertEqual(map_language('Moroccan Arabic', False).name, 'Arabic')
AssertionError: 'Moroccan Arabic' != 'Arabic'
- Moroccan Arabic
+ Arabic


----------------------------------------------------------------------
Ran 21 tests in 0.166s

FAILED (failures=1, errors=1)

```

**Comment by noumar** [comment]
Hi,

The [Compatibility](https://github.com/noumar/iso639#compatibility) section of the README clearly states:
>This library is aimed to be fully compatible with pycountry.languages v1.11 and before. In v1.12 they broke their own API and this library will not support the new API.

This library was written in 2014 as a drop-in-replacement with many improvements for pycountry.languages when v1.11 and 1.12 was current.

For now we won't support any further compatibility with pycountry.
